name: family_task
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.10.0
  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0

  # Hive Database
  hive: ^2.0.3
  hive_flutter: ^1.0.0

  # For Date Formatting
  intl: ^0.17.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  flutter_launcher_icons: ^0.9.0
  hive_generator: ^1.0.1

flutter_icons:
  ios: true
  android: 'launch_icon'
  image_path: 'Images/budget.png'

flutter:
  uses-material-design: true

  assets:
    - Images/
